### ISSUE TITLE
webpack.config.js不符合规范，如果我要自己编译的话

### ISSUE THREAD

**Issue by dorado-lmz** [Houfeng/faked#2]

**Comment by Houfeng** [comment]
@dorado-lmz 
嗯，现在是一个内部工具构建的（基于 Webpack），稍后构建工具也会开源出去。

**Comment by Houfeng** [comment]
@dorado-lmz 
faked 使用的构建工程 Dawn 已经开源，https://alibaba.github.io/dawn 可以使用  dawn 进行构建了
