### ISSUE TITLE
content-type="application/json"的请求被改为"plain/text"

### ISSUE THREAD

**Issue by dorado-lmz** [Houfeng/faked#3]
我在项目中使用faked.js，其中一些ajax请求我需要mock,这方面faked很出色。有些接口不需要faked mock,当我发送content-type="application/json"的请求时，faked给我改成"plain/text"。

经过查找，发现xhr.js文件109行_originSend函数中并没有将request `header拷贝到_originXhr对象。
```javascript
    this._originXhr.open(...this._openArgs);
    for(var entry of this._req.headers.entries()){
      if(typeof entry[0]==='string'){
        this.setRequestHeader(entry[0],entry[1])
      }
    }
```
添加上面的代码就可以了,不知道能否合并到主分支上

**Comment by Houfeng** [comment]
可以，创建一个 Pull Request 吧
